### ISSUE TITLE
Fetch and List 5 Stocks from API

### ISSUE THREAD

**Issue by kasulk** [kasulk/stocks-baby#16]
## Value proposition

As a user
I  can see a list of 5 stocks (fetched from the API) with recent prices
So that I always see recent market data

## Acceptance criteria

- [ ] Each stock's recent (API fetched) price is displayed

## Tasks

- [ ] Store API key in .env
- [ ] Remodel SWR to fetch intraday data (of the 5 stock tickers in db) from API
- [ ] Render last 60min. closing price to existing stock list
