### ISSUE TITLE
See all stocks and their data as cards

### ISSUE THREAD

**Issue by kasulk** [kasulk/stocks-baby#17]
## Value proposition

As a user
I  can see all stocks and their data currently in the DB as cards
So that I have a nice overview over the stocks and their data

## Acceptance criteria

- [ ] All stocks are displayed as cards
- [ ] Each stocks ticker is displayed
- [ ] Each stocks exchange is displayed
- [ ] Each stocks industry is displayed
- [ ] Each stocks dividends and dividend% is displayed
- [ ] Each stocks earnings per share is displayed
- [ ] Each stocks book value is displayed
- [ ] Each stocks 52 week high and low is displayed
- [ ] Each stocks analyst target price is displayed
- [ ] Bonus: Each stocks price is displayed

## Tasks

- [ ] Fetch all stocks data from API route and store it as a variable
- [ ] Drill props to the card component
- [ ] Render the props to the card
- [ ] Style stock cards
