### ISSUE TITLE
List all stocks of the S&P500 📑

### ISSUE THREAD

**Issue by kasulk** [kasulk/stocks-baby#2]
## Value proposition

As an user
I want to see a list of all stocks in the S&P500
So that I can scroll through all the stocks and check them out

## Description

/

## Acceptance criteria

- [ ] All stocks are displayed as a list
- [ ] Each stock ticker is displayed
- [ ] Each stock price is displayed
- [ ] Each stock EPS is displayed

## Tasks

- [ ]  Create new next.js project
- [ ]  Fetch all stocks with SWR in pages/index.js
- [ ]  Create the component StocksList to render a list
- [ ]  StocksList props: stocks
- [ ]  Create the component Stock
- [ ]  Stock props: ticker, name, price, eps
