### ISSUE TITLE
Mark stocks as favorite 📑

### ISSUE THREAD

**Issue by kasulk** [kasulk/stocks-baby#8]
## Value proposition

As a user
I  can mark stocks as favorites
So that I can find them easier

## Description

/

## Acceptance criteria

- [ ] The favorite-button is displayed next to the ticker/symbol
- [ ] The favorite-button is displayed in each entry in the list view
- [ ] Clicking the favorite-button on a non-favorite stock saves it as a favorite
- [ ] Clicking the favorite-button on a favorite stock removes it from favorites

## Tasks

- [ ] Create an additional state stocksInfo to save further information for stocks
- [ ] Make the stocksInfo state globally available for all pages
- [ ] Store the favorite flag in the stocksInfo
- [ ] Reference stocks by "ticker:exchange" in the additional state
- [ ] Create the component FavoriteButton
- [ ] FavoriteButton props: isFavorite, onToggleFavorite
- [ ] Render the FavoriteButton component in the StockList component
